# Generated by Django 5.2.11 on 2026-02-18 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=64, verbose_name='昵称')),
                ('author_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('author_website', models.URLField(blank=True, verbose_name='个人网站')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=16, verbose_name='审核状态')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP摘要')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审核通过时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论列表',
                'db_table': 'comment',
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_comment', '新评论通知'), ('reply', '回复通知')], max_length=24, verbose_name='通知类型')),
                ('target_email', models.EmailField(blank=True, max_length=254, verbose_name='目标邮箱')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('disabled', '已禁用')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blog.comment', verbose_name='关联评论')),
            ],
            options={
                'verbose_name': '评论通知任务',
                'verbose_name_plural': '评论通知任务',
                'db_table': 'comment_notification',
                'ordering': ['created_time'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status'], name='comment_article_623195_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_time'], name='comment_created_740bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='commentnotification',
            index=models.Index(fields=['status', 'next_retry_at'], name='comment_not_status_4904e3_idx'),
        ),
        migrations.AddIndex(
            model_name='commentnotification',
            index=models.Index(fields=['created_time'], name='comment_not_created_5cd262_idx'),
        ),
    ]
