# Generated by Django 5.2.11 on 2026-02-20 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_commentnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='项目标识')),
                ('github_url', models.URLField(max_length=500, unique=True, verbose_name='Github仓库地址')),
                ('short_description', models.CharField(max_length=255, verbose_name='一句话描述')),
                ('tech_stack', models.CharField(blank=True, max_length=255, verbose_name='技术栈')),
                ('highlights', models.TextField(verbose_name='项目亮点')),
                ('use_cases', models.TextField(verbose_name='使用场景')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否主推')),
                ('cover_image', models.ImageField(blank=True, upload_to='opensource_cover/', verbose_name='封面图')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '开源项目',
                'verbose_name_plural': '开源项目',
                'db_table': 'open_source_project',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetricSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True, verbose_name='快照日期')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Star数')),
                ('forks', models.PositiveIntegerField(default=0, verbose_name='Fork数')),
                ('last_commit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近提交时间')),
                ('sync_status', models.CharField(choices=[('success', '同步成功'), ('failed', '同步失败'), ('skipped', '已跳过')], db_index=True, default='skipped', max_length=16, verbose_name='同步状态')),
                ('sync_error', models.TextField(blank=True, verbose_name='同步错误')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='blog.opensourceproject', verbose_name='开源项目')),
            ],
            options={
                'verbose_name': '项目指标快照',
                'verbose_name_plural': '项目指标快照',
                'db_table': 'project_metric_snapshot',
                'ordering': ['-metric_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'metric_date'), name='uniq_project_metric_snapshot')],
            },
        ),
    ]
